text1 = input(">>> ")
text2 = input(">>> ")
text3 = input(">>> ")
set1 = set(map(int, text1.split()))
set2 = set(map(int, text2.split()))
set3 = set(map(int, text3.split()))
unique = sorted(set1 | set2 | set3)
common = sorted(set1 & set2 & set3)
print("Все уникальные числа по возрастанию:", unique)
print("Числа, которые есть в каждой строке:", common)