nums = input("Введите несколько цифр через пробел: ")
numbers = list(map(int, nums.split()))
rori = len(numbers)
total = sum(numbers)
maximum = max(numbers)
minimum = min(numbers)
average = sum(numbers)/rori
print("Количество чисел: ", rori)
print("Сумму всех чисел: ", total)
print("Максимальное число: ", maximum)
print("Минимальное число: ", minimum)
print("Среднее значение: ", round(average, 2))
